In [21]:
import pandas as pd, numpy as np, plotly,os

In [22]:
cur_dir = os.path.abspath('')
dataset_path = os.path.join(cur_dir,'..','Datasets/online+retail/Processed/online_retail_joined.pkl')

df = pd.read_pickle(dataset_path)

In [23]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067365,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
1067366,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
1067367,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
1067368,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
1067369,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [29]:
loyal_customers_df = df[df.CustomerID!=-1]

In [59]:
customer_recency = loyal_customers_df.groupby("CustomerID",as_index=False)["InvoiceDate"].max()
customer_recency.columns = ["CustomerID","LastPurchaseDate"]
customer_recency["LastPurchaseDate"] = customer_recency["LastPurchaseDate"].dt.normalize()

latest_purchase_date = customer_recency["LastPurchaseDate"].max()

customer_recency["Recency"] = customer_recency["LastPurchaseDate"].apply(
    lambda x: (latest_purchase_date - x).days)

In [61]:
customer_recency.head()

   CustomerID LastPurchaseDate  Recency
0     12346.0       2011-01-18      325
1     12347.0       2011-12-07        2
2     12348.0       2011-09-25       75
3     12349.0       2011-11-21       18
4     12350.0       2011-02-02      310

In [71]:
customer_freq = loyal_customers_df.groupby("CustomerID",as_index=False)["InvoiceDate"].nunique()
customer_freq.columns = ["CustomerID", "Frequency"]

In [72]:
customer_freq.head()

   CustomerID  Frequency
0     12346.0         17
1     12347.0          8
2     12348.0          5
3     12349.0          5
4     12350.0          1

In [73]:
loyal_customers_df["TotalPrice"] = loyal_customers_df["UnitPrice"]*loyal_customers_df["Quantity"]

customer_monetary = loyal_customers_df.groupby("CustomerID",as_index=False)["TotalPrice"].sum()
customer_monetary.columns = ["CustomerID", "Monetary"]

In [74]:
customer_monetary.head()

   CustomerID  Monetary
0     12346.0    -64.68
1     12347.0   5598.52
2     12348.0   2019.40
3     12349.0   4270.48
4     12350.0    314.60

In [75]:
loyal_customers_df.loc[(loyal_customers_df["CustomerID"]==12346.0)
    &
    (loyal_customers_df["Quantity"]<0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346.0,United Kingdom,-77183.60
612989,C495800,ADJUST,ADJUSTMENT BY JOHN ON 26/01/2010 16,-1,2010-01-26 17:27:00,103.50,12346.0,United Kingdom,-103.50
797495,C514024,M,MANUAL,-1,2010-06-30 11:22:00,5.18,12346.0,United Kingdom,-5.18
797496,C514024,M,MANUAL,-1,2010-06-30 11:22:00,12.94,12346.0,United Kingdom,-12.94
797497,C514024,M,MANUAL,-1,2010-06-30 11:22:00,4.66,12346.0,United Kingdom,-4.66
797498,C514024,M,MANUAL,-1,2010-06-30 11:22:00,12.94,12346.0,United Kingdom,-12.94
797499,C514024,M,MANUAL,-1,2010-06-30 11:22:00,25.88,12346.0,United Kingdom,-25.88
797500,C514024,M,MANUAL,-3,2010-06-30 11:22:00,12.94,12346.0,United Kingdom,-38.82
797501,C514024,M,MANUAL,-1,2010-06-30 11:22:00,1.15,12346.0,United Kingdom,-1.15
797502,C514024,M,MANUAL,-4,2010-06-30 11:22:00,13.22,12346.0,United Kingdom,-52.88
797503,C514024,M,MANUAL,-1,2010-06-30 11:22:00,31.78,12346.0,United Kingdom,-31.78
797504,C514024,M,MANUAL,-1,2010-06-30 11:22:00,142.31,12346.0,United Kingdom,-142.31
911957,C525099,D,DISCOUNT,-1,2010-10-04 09:54:00,1.00,12346.0,United Kingdom,-1.00
913688,C525274,TEST001,THIS IS A TEST PRODUCT.,-1,2010-10-04 16:33:00,4.50,12346.0,United Kingdom,-4.50

In [77]:
loyal_customers_df.loc[(loyal_customers_df["CustomerID"]==12347.0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
14938,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347.0,Iceland,25.20
14939,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347.0,Iceland,17.00
14940,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347.0,Iceland,39.00
14941,537626,22492,MINI PAINT SET VINTAGE,36,2010-12-07 14:57:00,0.65,12347.0,Iceland,23.40
14942,537626,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12,2010-12-07 14:57:00,1.25,12347.0,Iceland,15.00
...,...,...,...,...,...,...,...,...,...
1059811,537626,21064,BOOM BOX SPEAKER BOYS,6,2010-12-07 14:57:00,5.95,12347.0,Iceland,35.70
1059812,537626,21731,RED TOADSTOOL LED NIGHT LIGHT,12,2010-12-07 14:57:00,1.65,12347.0,Iceland,19.80
1059813,537626,84558A,3D DOG PICTURE PLAYING CARDS,24,2010-12-07 14:57:00,2.95,12347.0,Iceland,70.80
1059814,537626,20780,BLACK EAR MUFF HEADPHONES,12,2010-12-07 14:57:00,4.65,12347.0,Iceland,55.80
1059815,537626,20782,CAMOUFLAGE EAR MUFF HEADPHONES,6,2010-12-07 14:57:00,5.49,12347.0,Iceland,32.94